name: frontend-ci

on:
  push:
    branches: [main, feat/snapthumb-v1-1]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 9.15.9 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        timeout-minutes: 5

      # build once
      - name: Build application
        run: pnpm run build
        timeout-minutes: 5

      # start local preview server for e2e (no Vercel URL needed)
      - name: Install wait-on
        run: pnpm add -D wait-on
        timeout-minutes: 2

      - name: Start preview server
        run: |
          echo "Starting preview server..."
          # Try starting the server with more explicit options
          pnpm run preview -- --port 4173 --host 0.0.0.0 &
          SERVER_PID=$!
          echo "Server PID: $SERVER_PID"
          
          # Wait a bit for the server to initialize
          sleep 5
          
          echo "Waiting for server to start..."
          # Try multiple approaches to check if server is ready
          for i in {1..30}; do
            if curl -f http://127.0.0.1:4173 > /dev/null 2>&1; then
              echo "Server is ready after $((i*2)) seconds!"
              break
            fi
            echo "Attempt $i: Server not ready yet, waiting..."
            sleep 2
            if [ $i -eq 30 ]; then
              echo "Server failed to start after 60 seconds"
              echo "Checking if server process is still running..."
              ps aux | grep preview || echo "No preview process found"
              exit 1
            fi
          done
          echo "Server health check passed!"
        timeout-minutes: 5

      # playwright with caching and optimization
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers (Chromium only for CI)
        run: pnpm exec playwright install chromium --with-deps
        timeout-minutes: 10

      - name: Run Playwright tests (CI optimized)
        run: pnpm exec playwright test ci-basic.spec.ts --project=chromium
        timeout-minutes: 5
        env:
          # ensure tests use the local server
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:4173

      # lighthouse on built dist
      - name: Run Lighthouse CI
        run: npx @lhci/cli autorun --collect.staticDistDir=dist
        timeout-minutes: 5
