name: frontend-ci

on:
  push:
    branches: [ main, feat/snapthumb-v1-1 ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { version: 9.15.9 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: pnpm install --frozen-lockfile

      # build once
      - run: pnpm run build

      # start local preview server for e2e (no Vercel URL needed)
      - run: pnpm add -D wait-on
      - run: |
          pnpm run preview -- --port 4173 &
          npx wait-on http://127.0.0.1:4173

      # playwright
      - run: pnpm exec playwright install --with-deps
      - run: pnpm exec playwright test
        env:
          # ensure tests use the local server
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:4173

      # lighthouse on built dist
      - run: npx @lhci/cli autorun --collect.staticDistDir=dist
